# Generated by Django 3.2.8 on 2021-10-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
